apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  name: pvc-e0d33dec-8119-48f7-b695-d74d88b22619
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name:  datadir-0-kafka-cp-kafka-0
    namespace: kafka
  hostPath:
    path: /var/lib/rancher/k3s/storage/pvc-e0d33dec-8119-48f7-b695-d74d88b22619_kafka_datadir-0-kafka-cp-kafka-0
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem

